name: AWS CLI
on: 
 push:

jobs:
   deploy:
    runs-on: ubuntu-latest
    container: ruby:2.6.6
    steps:
#      - name: Checkout
#        uses: actions/checkout@v2

#      - name: Setup SAM
#        uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Check for AWS CLI
        run: aws cloudformation help
