name: learn-github-actions
on: 
 push:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  echo-commit-message-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set commit title
        run: echo COMMIT_MESSAGE=$(git log -n 1 --pretty=format:%s) >> $GITHUB_ENV
      - name: Print GitHub Env
        run: cat $GITHUB_ENV
      - name: Echo commit title
        run: echo ${COMMIT_MESSAGE}

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry: [ test ]
    steps:
      - run: echo ${{ matrix.entry }}     
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  test-cache:
    runs-on: ubuntu-latest
    steps:
     - name: bundle cache
       uses: actions/cache@v2
       id: bundle-cache
       with:
          path: |
            vendor/cache
            vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-
