name: learn-github-actions
on: 
 push:

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        workspace: [default]
        environment: [staging, production]
    env:
      WORKSPACE: ${{ matrix.workspace }}
      ENVIRONMENT: ${{ matrix.environment }}

    runs-on: ubuntu-latest
   
    steps:
      - name: Print env
        run: echo ${{ env.WORKSPACE }} ${{ env.ENVIRONMENT }}

      - name: Print matrix
        run: echo ${{ matrix.workspace }} ${{ matrix.environment }}
      
      - name: Print staging (matrix)
        if: ${{ matrix.environment == 'staging' }}
        run: |
          echo "Staging"

      - name: Print staging (env)
        if: ${{ env.ENVIRONMENT == 'staging' }}
        run: |
          echo "Staging"

      - name: Print production (matrix)
        if: ${{ matrix.environment == 'production' }}
        run: |
          echo "production"

      - name: Print prod (env)
        if: ${{ env.ENVIRONMENT == 'production' }}
        run: |
          echo "production"
