name: learn-github-actions
on: 
 push:
 workflow_call:
   inputs:
     greet-name-matrix:
       description: "The matrix of who to greet"
       default: '[ alice, bob, charlie ]'
       required: false
       type: string

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  greet-user:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        greet-name: ${{ fromJson(inputs.greet-name-matrix) }}
    steps:
      - run: |
          if [[ ${name} == "alice" ]]; then
            secret=${{ secrets.alice }}
          elif [[ ${name} == "bob" ]]; then
            secret=${{ secrets.bob }}
          fi
      - run: echo "hello ${{ matrix.greet-name }}${secret}"
