name: reusable-workflow
on: 
  workflow_call:
    inputs:
      greet-name-matrix:
        description: "The matrix of who to greet"
        default: '[ alice, bob, charlie ]'
        required: false
        type: string
    secrets:
      ALICE:
      BOB:

jobs:
  greet-user:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        greet-name: ${{ fromJson(inputs.greet-name-matrix) }}
    steps:
      - run: echo ${{ secrets.TEST }}
      - run: |
          if [[ "${{ matrix.greet-name }}" == "alice" ]]; then
            echo "secret_txt= hard-coded text ${{ secrets.ALICE }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.greet-name }}" == "bob" ]]; then
            secret_txt=${{ secrets.BOB }}
            echo "secret_txt= ${{ secrets.BOB }}" >> $GITHUB_ENV
          fi
      - run: echo "hello ${{ matrix.greet-name }}${secret_txt}"
